# Generated by Django 4.2 on 2023-04-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_rental_backend', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='review',
            name='review',
            field=models.CharField(default='Nice', max_length=5000),
            preserve_default=False,
        ),
    ]
