# Generated by Django 4.2 on 2023-04-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_rental_backend', '0003_review_rating_review_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='movie',
            name='review',
            field=models.CharField(default='great movie', max_length=5000),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
