# Generated by Django 4.2 on 2023-04-20 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_rental_backend', '0011_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='stars',
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.DecimalField(decimal_places=3, default=3.5, max_digits=4),
            preserve_default=False,
        ),
    ]
