# Generated by Django 4.2 on 2023-04-20 05:11

from django.db import migrations
import movie_rental_backend.models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_rental_backend', '0012_remove_review_stars_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
        migrations.AddField(
            model_name='review',
            name='stars',
            field=movie_rental_backend.models.StarRatingField(default=4),
            preserve_default=False,
        ),
    ]
