# Generated by Django 4.2 on 2023-04-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_rental_backend', '0013_remove_review_rating_review_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='avg_star',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
