# Generated by Django 4.2 on 2023-04-20 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_rental_backend', '0014_review_avg_star'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='avg_star',
        ),
    ]
